### ISSUE TITLE
Ingressroute Load Balancing and Healthcheck settings has no affect to upstream service choices

### ISSUE THREAD

**Issue by yutaokaz** [heptio/gimbal#186]
**Is this a BUG REPORT, PERFORMANCE REPORT or FEATURE REQUEST?**:

BUG REPORT.

**What happened**:

I tried to set load balancing method as strategy at ingressroute.yaml file, but each method looks no affects to Upstream RPS nor Upstream CPS in Grafana dashboard. And (includes defaults) RoundRobin method sometimes choice same upstream service from 1 gimbal pod.
I succeeded to set Healthcheck path, but even if upstream service returns 503 response for envoy healthchecking, envoy continues choice this service.

**What you expected to happen**:

I considering heptio/contour couldn't set envoy correctly (envoyproxy's bug?), or I just misunderstood.

**How to reproduce it (as minimally and precisely as possible)**:

Bellow is my ingressroute.yaml.

```yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: yj-yutaokaz-ingressroute
  namespace: yj-yutaokaz
spec:
  virtualhost:
    fqdn: yj-yutaokaz.local
  routes:
    - match: /
      services:
        - name: k8s01-yutaokaz-service80
          port: 80
          strategy: RoundRobin
        - name: os01-yutaokaz-service80
          port: 80
          strategy: RoundRobin
          healthCheck:
            path: /503.php
```

**Anything else we need to know?**:

I reading below documentation to configure ingressroute.
https://github.com/heptio/contour/blob/v0.6.0-beta.1/design/ingressroute-design.md

**Environment**:

- Gimbal version (Gimbal git repository tag):
https://github.com/heptio/gimbal/tree/release-0.3.0-beta.1
- Contour version:
gcr.io/heptio-images/contour:v0.6.0-beta.1
- kubernetes-discoverer version:
- openstack-discoverer version (if applicable):
gcr.io/heptio-images/gimbal-discoverer:v0.3.0-beta.1
